name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/

  train_quantize:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: python app/train_model.py
      - name: Quantize model
        run: python app/quantize.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: |
            models/model.joblib
            models/raw_params.joblib
            models/quantized_params.joblib

  docker_build_test:
    needs: train_quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pipeline-artifacts
          path: artifacts/
      - name: Build Docker image
        run: docker build -t mlops-regression .
      - name: Test Docker container
        run:  docker run --rm major-exam-mlops 
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Tag Docker image
        run: docker tag mlops-regression ${{ secrets.DOCKER_USERNAME }}/mlops-regression:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops-regression:latest